//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.11 at 04:30:18 PM CET 
//


package org.oasis_open.docs.ebxml_bp.ebbp_signals_2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.oasis_open.docs.ebxml_bp.ebbp_signals_2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.oasis_open.docs.ebxml_bp.ebbp_signals_2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link SignalIdentificationInformation }
     * 
     */
    public SignalIdentificationInformation createSignalIdentificationInformation() {
        return new SignalIdentificationInformation();
    }

    /**
     * Create an instance of {@link PartyInfoType }
     * 
     */
    public PartyInfoType createPartyInfoType() {
        return new PartyInfoType();
    }

    /**
     * Create an instance of {@link RoleType }
     * 
     */
    public RoleType createRoleType() {
        return new RoleType();
    }

    /**
     * Create an instance of {@link ProcessSpecificationInfoType }
     * 
     */
    public ProcessSpecificationInfoType createProcessSpecificationInfoType() {
        return new ProcessSpecificationInfoType();
    }

    /**
     * Create an instance of {@link Exception.ExceptionType }
     * 
     */
    public Exception.ExceptionType createExceptionExceptionType() {
        return new Exception.ExceptionType();
    }

    /**
     * Create an instance of {@link ReceiptAcknowledgement }
     * 
     */
    public ReceiptAcknowledgement createReceiptAcknowledgement() {
        return new ReceiptAcknowledgement();
    }

    /**
     * Create an instance of {@link NonRepudiationInformation }
     * 
     */
    public NonRepudiationInformation createNonRepudiationInformation() {
        return new NonRepudiationInformation();
    }

    /**
     * Create an instance of {@link MessagePartNRInformation }
     * 
     */
    public MessagePartNRInformation createMessagePartNRInformation() {
        return new MessagePartNRInformation();
    }

    /**
     * Create an instance of {@link AcceptanceAcknowledgement }
     * 
     */
    public AcceptanceAcknowledgement createAcceptanceAcknowledgement() {
        return new AcceptanceAcknowledgement();
    }

}
