//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.11 at 04:30:18 PM CET 
//


package org.oasis_open.docs.ebxml_bp.ebbp_signals_2;

import java.io.Serializable;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2001.xmlschema.Adapter1;


/**
 * This defines the content structure for identiying various parameters
 *                 pertaining to the business signal. "OriginalMessageIdentifier" captures the value of
 *                 the transport message identifier for original message to which this business signal
 *                 is being sent. If business message has an identifier, that can be captured by the
 *                 "OriginalDocumentIdentifier" attribute. "OriginalMessageDateTime" is the time when
 *                 the original message was sent. "ThisMessageDateTime" is the time when this signal
 *                 message is being sent. The following optional elements are there to provide access
 *                 to information that can be used by processing logic outside the business process
 *                 engine. One example of this could be a monitoring application which can use this
 *                 information to provide status of a collaboration. "FromPartyInfo" describes the
 *                 party id that is sending the signal message. "ToPartyInfo" describes the party id
 *                 that is being sent the signal message. The roles described below are based on the
 *                 implicit relationship between the partner sending the signal message and the partner
 *                 who sent the original message to which this particular signal is being sent. The
 *                 role relationship between partner sending the business message and the partner
 *                 receiving it is captured in the process definition (ebBP). "FromRole" captures the
 *                 role being played by the party that is sending the signal message. "ToRole" captures
 *                 the role played by the party that is being sent the signal message.
 *                 "ProcessSpecificationInfo" type descibes the process information (ebBP) which
 *                 defines the runtime collaborations for which this signal is being sent
 *                 "CollaborationIdentifier" is the unique identifer that associates the signal with a
 *                 particular collaboration. This could come from the business message itself or in
 *                 case of ebXML MSH, could be the messaging level header "ConversationId"
 *                 "BusinessActivityIdentifier" identifies the business Requesting or Responding
 *                 activity to which this signal is being sent. This would identify the
 *                 "BusinessAction" from the process definition (ebBP) and could be implemented using
 *                 the "name" attribute on either the RequestingBusinessActivity or the
 *                 RespondingBusinessActivity.
 * 
 * <p>Java class for SignalIdentificationInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignalIdentificationInformation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OriginalMessageIdentifier" type="{http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0}non-empty-string"/&gt;
 *         &lt;element name="OriginalDocumentIdentifier" type="{http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0}non-empty-string" minOccurs="0"/&gt;
 *         &lt;element name="OriginalMessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="ThisMessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="FromPartyInfo" type="{http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0}PartyInfoType" minOccurs="0"/&gt;
 *         &lt;element name="ToPartyInfo" type="{http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0}PartyInfoType" minOccurs="0"/&gt;
 *         &lt;element name="FromRole" type="{http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0}RoleType" minOccurs="0"/&gt;
 *         &lt;element name="ToRole" type="{http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0}RoleType" minOccurs="0"/&gt;
 *         &lt;element name="ProcessSpecificationInfo" type="{http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0}ProcessSpecificationInfoType" minOccurs="0"/&gt;
 *         &lt;element name="CollaborationIdentifier" type="{http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0}non-empty-string" minOccurs="0"/&gt;
 *         &lt;element name="BusinessActivityIdentifier" type="{http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0}non-empty-string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignalIdentificationInformation", propOrder = {
    "originalMessageIdentifier",
    "originalDocumentIdentifier",
    "originalMessageDateTime",
    "thisMessageDateTime",
    "fromPartyInfo",
    "toPartyInfo",
    "fromRole",
    "toRole",
    "processSpecificationInfo",
    "collaborationIdentifier",
    "businessActivityIdentifier"
})
@XmlSeeAlso({
    AcceptanceAcknowledgement.class,
    ReceiptAcknowledgement.class,
    Exception.class
})
public class SignalIdentificationInformation
    implements Serializable
{

    @XmlElement(name = "OriginalMessageIdentifier", required = true)
    protected String originalMessageIdentifier;
    @XmlElement(name = "OriginalDocumentIdentifier")
    protected String originalDocumentIdentifier;
    @XmlElement(name = "OriginalMessageDateTime", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Date originalMessageDateTime;
    @XmlElement(name = "ThisMessageDateTime", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Date thisMessageDateTime;
    @XmlElement(name = "FromPartyInfo")
    protected PartyInfoType fromPartyInfo;
    @XmlElement(name = "ToPartyInfo")
    protected PartyInfoType toPartyInfo;
    @XmlElement(name = "FromRole")
    protected RoleType fromRole;
    @XmlElement(name = "ToRole")
    protected RoleType toRole;
    @XmlElement(name = "ProcessSpecificationInfo")
    protected ProcessSpecificationInfoType processSpecificationInfo;
    @XmlElement(name = "CollaborationIdentifier")
    protected String collaborationIdentifier;
    @XmlElement(name = "BusinessActivityIdentifier")
    protected String businessActivityIdentifier;

    /**
     * Gets the value of the originalMessageIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalMessageIdentifier() {
        return originalMessageIdentifier;
    }

    /**
     * Sets the value of the originalMessageIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalMessageIdentifier(String value) {
        this.originalMessageIdentifier = value;
    }

    /**
     * Gets the value of the originalDocumentIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalDocumentIdentifier() {
        return originalDocumentIdentifier;
    }

    /**
     * Sets the value of the originalDocumentIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalDocumentIdentifier(String value) {
        this.originalDocumentIdentifier = value;
    }

    /**
     * Gets the value of the originalMessageDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getOriginalMessageDateTime() {
        return originalMessageDateTime;
    }

    /**
     * Sets the value of the originalMessageDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalMessageDateTime(Date value) {
        this.originalMessageDateTime = value;
    }

    /**
     * Gets the value of the thisMessageDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getThisMessageDateTime() {
        return thisMessageDateTime;
    }

    /**
     * Sets the value of the thisMessageDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThisMessageDateTime(Date value) {
        this.thisMessageDateTime = value;
    }

    /**
     * Gets the value of the fromPartyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PartyInfoType }
     *     
     */
    public PartyInfoType getFromPartyInfo() {
        return fromPartyInfo;
    }

    /**
     * Sets the value of the fromPartyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyInfoType }
     *     
     */
    public void setFromPartyInfo(PartyInfoType value) {
        this.fromPartyInfo = value;
    }

    /**
     * Gets the value of the toPartyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PartyInfoType }
     *     
     */
    public PartyInfoType getToPartyInfo() {
        return toPartyInfo;
    }

    /**
     * Sets the value of the toPartyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyInfoType }
     *     
     */
    public void setToPartyInfo(PartyInfoType value) {
        this.toPartyInfo = value;
    }

    /**
     * Gets the value of the fromRole property.
     * 
     * @return
     *     possible object is
     *     {@link RoleType }
     *     
     */
    public RoleType getFromRole() {
        return fromRole;
    }

    /**
     * Sets the value of the fromRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleType }
     *     
     */
    public void setFromRole(RoleType value) {
        this.fromRole = value;
    }

    /**
     * Gets the value of the toRole property.
     * 
     * @return
     *     possible object is
     *     {@link RoleType }
     *     
     */
    public RoleType getToRole() {
        return toRole;
    }

    /**
     * Sets the value of the toRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleType }
     *     
     */
    public void setToRole(RoleType value) {
        this.toRole = value;
    }

    /**
     * Gets the value of the processSpecificationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessSpecificationInfoType }
     *     
     */
    public ProcessSpecificationInfoType getProcessSpecificationInfo() {
        return processSpecificationInfo;
    }

    /**
     * Sets the value of the processSpecificationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessSpecificationInfoType }
     *     
     */
    public void setProcessSpecificationInfo(ProcessSpecificationInfoType value) {
        this.processSpecificationInfo = value;
    }

    /**
     * Gets the value of the collaborationIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollaborationIdentifier() {
        return collaborationIdentifier;
    }

    /**
     * Sets the value of the collaborationIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollaborationIdentifier(String value) {
        this.collaborationIdentifier = value;
    }

    /**
     * Gets the value of the businessActivityIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessActivityIdentifier() {
        return businessActivityIdentifier;
    }

    /**
     * Sets the value of the businessActivityIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessActivityIdentifier(String value) {
        this.businessActivityIdentifier = value;
    }

}
